languageCode = "en-us"
title = "Brain Baking"
baseurl = "https://brainbaking.com/"
enableEmoji = true
theme = "minimal"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-45748221-1"
publishDir = "docs"

[taxonomies]
  tag = "tags"

[params]
    description = "Freshly baked thoughts."
    # see single.html, DisqusShortname also needed
    disableComments = true
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    highlight = true
    highlightStyle = "paraiso-dark"
    highlightLanguages = ["c#", "java", "scala", "javascript"]
    font = "Open Sans"
    copyright = "No <i class='fa fa-copyright'></i> reserved - sharing is caring. <i class='fa fa-github'></i> <a href='https://github.com/wgroeneveld/brainbaking/'>Hack away</a>! <i class='fa fa-lightbulb-o'></i> <a href='/'>Brainbaking</a>"

[Author]
  name = "Wouter Groeneveld"
  email = "wouter.groeneveld@gmail.com"

[[menu.main]]
    name = "Tech Blog"
    pre = "<i class='fa fa-file-code-o'></i>"
    url = "/post"
    weight = 1

[[menu.main]]
    name = "Essays"
    pre = "<i class='fa fa-book'></i>"
    url = "/essays"
    weight = 2

[[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags'></i>"
    url = "/tags"
    weight = 3

[[menu.mainright]]
    name = "About Me"
    pre = "<i class='fa fa-user'></i>" 
    url = "/about"
    weight = 4

[[menu.mainright]]
    name = "Teaching"
    pre = "<i class='fa fa-graduation-cap'></i>"
    url = "/teaching"
    weight = 5

